version: "3.4"

services:
  product-api:
    build:
      context: back-end
      dockerfile: Dockerfile
    container_name: product-back-end
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    ports:
      - "5156:80"
  
  product-front:
    build:
      context: front-end
      dockerfile: Dockerfile
    container_name: product-front-end
    ports:
      - "4200:4200"