version: "3.4"

services:
  product-api:
    build:
      context: back-end
      dockerfile: Dockerfile
    container_name: product-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    ports:
      - "7135:80"